<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Exe</OutputType>
		<UserSecretsId>7a340509-34ac-408b-bafd-244d3ddcddf3</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\TravelBlogs.Infrastructure\TravelBlogs.Infrastructure.Migrators\TravelBlogs.Infrastructure.Migrators.csproj" />
		<ProjectReference Include="..\..\TravelBlogs.Infrastructure\TravelBlogs.Infrastructure\TravelBlogs.Infrastructure.csproj" />
	</ItemGroup>

</Project>