<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.AutoHistory" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TravelBlogs.Core\TravelBlogs.Core.Application\TravelBlogs.Core.Application.csproj" />
    <ProjectReference Include="..\..\TravelBlogs.Core\TravelBlogs.Core.Domain\TravelBlogs.Core.Domain.csproj" />
    <ProjectReference Include="..\..\TravelBlogs.Core\TravelBlogs.Core.Shared\TravelBlogs.Core.Shared.csproj" />
  </ItemGroup>

</Project>
