<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="8.0.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravelBlogs.Core.Domain\TravelBlogs.Core.Domain.csproj" />
    <ProjectReference Include="..\TravelBlogs.Core.Shared\TravelBlogs.Core.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dto\Common\" />
  </ItemGroup>

</Project>
